### ISSUE TITLE
Add searching for a user's comments

### ISSUE THREAD

**Issue by ddobrev** [sowdust/sowdust.github.io#3]
The old Facebook Graph Search could find a user's comments, it was very useful to keep track of public figures, such as entrepreneurs with new ideas and developments.

**Comment by Gjiada** [comment]
With this new extension is possible to search all the comment of a given user to posts and video in a given time, for example in a week? Which is the correct query?

**Comment by sowdust** [comment]
You can find information about the extension here: https://github.com/sowdust/searchbook/blob/master/README.md

**Comment by Gjiada** [comment]
I have already read the article but I could not manage to get any result :( Are you planning a next article with more details? Are you Italian by the way? Me too :)

**Comment by sowdust** [comment]
> 
> 
> I have already read the article but I could not manage to get any result :( Are you planning a next article with more details? Are you Italian by the way? Me too :)

write me an email (you can find the address on the webpage) and tell me what you need to do
