### ISSUE TITLE
Clicking on "See all" will discard date filter for photos

### ISSUE THREAD

**Issue by YvdW** [sowdust/sowdust.github.io#4]
Here are the reproduction steps:

1. Select photos from the dropdown menu on graph.tips/facebook.html
2. Add a date filter, e.g. rp_creation_time {"start_year":"2014","start_month":"2014-10","end_year":"2014","end_month":"2014-10","start_day":"2014-10-11","end_day":"2014-10-13"}
3. Now you add a keyword to find pictures from Times Square or a different location or object.
4. Search, this will open a new window. In this new window you will see 9 pictures grouped horizontally by groups of 3. All these 9 photos are of the dates you specified. 
5. If you want to find more pictures, however, you will have to click on "See all" and this will discard the date filter.
That is, the full URL that you get when you add the filter and **before** you click on _See all_  is this:
`https://www.facebook.com/search/photos/?q=times%20square&epa=FILTERS&filters=eyJycF9jcmVhdGlvbl90aW1lIjoie1wibmFtZVwiOlwiY3JlYXRpb25fdGltZVwiLFwiYXJnc1wiOlwie1xcXCJzdGFydF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcInN0YXJ0X21vbnRoXFxcIjpcXFwiMjAxNC0xMFxcXCIsXFxcImVuZF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcImVuZF9tb250aFxcXCI6XFxcIjIwMTQtMTBcXFwiLFxcXCJzdGFydF9kYXlcXFwiOlxcXCIyMDE0LTEwLTExXFxcIixcXFwiZW5kX2RheVxcXCI6XFxcIjIwMTQtMTAtMTNcXFwifVwifSJ9`

**After** you click on _See all_:
`https://www.facebook.com/search/str/times+square/photos-keyword?f=Abp2v7X7McNmyTMs0PsXMA78jr7y72ulkoNYRGspBWTnS5wNxNgnll9IHP2xGOl5fLoXTkPbLNNVZYYEBuvOyedNhiENFM2PcrsQms0NxtF7SwIk_7sQARI4S6tRYMtpxRg&rp_creation_time=%7B%22name%22%3A%22creation_time%22%2C%22args%22%3A%22%7B%5C%22start_year%5C%22%3A%5C%222014%5C%22%2C%5C%22start_month%5C%22%3A%5C%222014-10%5C%22%2C%5C%22end_year%5C%22%3A%5C%222014%5C%22%2C%5C%22end_month%5C%22%3A%5C%222014-10%5C%22%2C%5C%22start_day%5C%22%3A%5C%222014-10-11%5C%22%2C%5C%22end_day%5C%22%3A%5C%222014-10-13%5C%22%7D%22%7D&epa=SEE_MORE`

As you will see when you click on any of the pictures, the date filter doesn't work after that.

I found a workaround, however. You will need to copy everything what comes after _f=_ and paste it in the previous URL. That is, you will copy `f=Abp2v7X7McNmyTMs0PsXMA78jr7y72ulkoNYRGspBWTnS5wNxNgnll9IHP2xGOl5fLoXTkPbLNNVZYYEBuvOyedNhiENFM2PcrsQms0NxtF7SwIk_7sQARI4S6tRYMtpxRg`

after the keyword
`q=times%20square&
`
and in front of
`&epa=FILTERS&`

`https://www.facebook.com/search/photos/?q=times%20square&f=Abp2v7X7McNmyTMs0PsXMA78jr7y72ulkoNYRGspBWTnS5wNxNgnll9IHP2xGOl5fLoXTkPbLNNVZYYEBuvOyedNhiENFM2PcrsQms0NxtF7SwIk_7sQARI4S6tRYMtpxRg&epa=FILTERS&filters=eyJycF9jcmVhdGlvbl90aW1lIjoie1wibmFtZVwiOlwiY3JlYXRpb25fdGltZVwiLFwiYXJnc1wiOlwie1xcXCJzdGFydF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcInN0YXJ0X21vbnRoXFxcIjpcXFwiMjAxNC0xMFxcXCIsXFxcImVuZF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcImVuZF9tb250aFxcXCI6XFxcIjIwMTQtMTBcXFwiLFxcXCJzdGFydF9kYXlcXFwiOlxcXCIyMDE0LTEwLTExXFxcIixcXFwiZW5kX2RheVxcXCI6XFxcIjIwMTQtMTAtMTNcXFwifVwifSJ9`

So the link is:
https://www.facebook.com/search/photos/?q=times%20square&f=Abp2v7X7McNmyTMs0PsXMA78jr7y72ulkoNYRGspBWTnS5wNxNgnll9IHP2xGOl5fLoXTkPbLNNVZYYEBuvOyedNhiENFM2PcrsQms0NxtF7SwIk_7sQARI4S6tRYMtpxRg&epa=FILTERS&filters=eyJycF9jcmVhdGlvbl90aW1lIjoie1wibmFtZVwiOlwiY3JlYXRpb25fdGltZVwiLFwiYXJnc1wiOlwie1xcXCJzdGFydF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcInN0YXJ0X21vbnRoXFxcIjpcXFwiMjAxNC0xMFxcXCIsXFxcImVuZF95ZWFyXFxcIjpcXFwiMjAxNFxcXCIsXFxcImVuZF9tb250aFxcXCI6XFxcIjIwMTQtMTBcXFwiLFxcXCJzdGFydF9kYXlcXFwiOlxcXCIyMDE0LTEwLTExXFxcIixcXFwiZW5kX2RheVxcXCI6XFxcIjIwMTQtMTAtMTNcXFwifVwifSJ9

You can also read the Twitter thread that I wrote about it.
https://twitter.com/y_vdw/status/1143940284318924806

**Comment by YvdW** [comment]
Maybe this will be difficult to automate with the website but you might be able to intercept this with your searchbook Firefox extension?

**Comment by sowdust** [comment]
Thanks for the notification. I suggest using searchbook for now (i.e. setting the query from the extension instead of using the html page), at least for as long as it works. If and when that method will become unusable, we'll see another good way to do what you want ;)
